Repository hashicorp/terraform-plugin-docs, pull requests merged in 2024-01, with the labels that each got.

#314 Implement `migrate` sub-command
  .changes/unreleased/FEATURES-20231220-141244.yaml
  README.md
  cmd/tfplugindocs/main_test.go
  cmd/tfplugindocs/testdata/scripts/schema-json/migrate/time_provider_success_docs_website.txtar
  cmd/tfplugindocs/testdata/scripts/schema-json/migrate/time_provider_success_legacy_website.txtar
  go.mod
  go.sum
  internal/cmd/migrate.go
  internal/cmd/run.go
  internal/provider/migrate.go
  internal/provider/template.go
  internal/provider/util.go
Labels: enhancement

#322 deps: Migrate to github.com/hashicorp/cli
  go.mod
  go.sum
  internal/cmd/run.go
  internal/provider/generate.go
  internal/provider/generate_test.go
  internal/provider/migrate.go
  internal/provider/validate.go
Labels: dependencies

#324 Document the default behavior of `--tf-version` and usage of Terraform binary
  README.md
  internal/cmd/generate.go
Labels: documentation

#328 Add Support for Provider-defined Function Documentation
  .changes/unreleased/ENHANCEMENTS-20240122-160317.yaml
  .changes/unreleased/FEATURES-20240122-160026.yaml
  .changes/unreleased/FEATURES-20240122-160050.yaml
  README.md
  cmd/tfplugindocs/testdata/scripts/provider-build/generate/framework_provider_success_generic_templates.txtar
  cmd/tfplugindocs/testdata/scripts/provider-build/generate/framework_provider_success_named_templates.txtar
  cmd/tfplugindocs/testdata/scripts/provider-build/generate/framework_provider_success_no_templates.txtar
  cmd/tfplugindocs/testdata/scripts/provider-build/generate/null_provider_success.txtar
  cmd/tfplugindocs/testdata/scripts/schema-json/generate/framework_provider_success_generic_templates.txtar
  cmd/tfplugindocs/testdata/scripts/schema-json/generate/framework_provider_success_legacy_docs.txtar
  cmd/tfplugindocs/testdata/scripts/schema-json/generate/framework_provider_success_named_templates.txtar
  cmd/tfplugindocs/testdata/scripts/schema-json/generate/framework_provider_success_no_templates.txtar
  cmd/tfplugindocs/testdata/scripts/schema-json/generate/framework_provider_success_static_files.txtar
  cmd/tfplugindocs/testdata/scripts/schema-json/generate/null_provider_success.txtar
  cmd/tfplugindocs/testdata/scripts/schema-json/migrate/time_provider_success_docs_website.txtar
  cmd/tfplugindocs/testdata/scripts/schema-json/migrate/time_provider_success_legacy_website.txtar
  functionmd/render.go
  functionmd/render_test.go
  functionmd/testdata/example_arguments.md
  functionmd/testdata/example_signature.md
  functionmd/testdata/example_vararg.md
  functionmd/testdata/function_signature.schema.json
  internal/provider/generate.go
  internal/provider/migrate.go
  internal/provider/template.go
  internal/provider/validate.go
Labels: enhancement

#330 Output relative paths for `migrate` code template references
  .changes/unreleased/BUG FIXES-20240124-131519.yaml
  cmd/tfplugindocs/testdata/scripts/schema-json/migrate/time_provider_success_docs_website.txtar
  cmd/tfplugindocs/testdata/scripts/schema-json/migrate/time_provider_success_legacy_website.txtar
  internal/provider/migrate.go
  internal/provider/util.go
Labels: bug, command/migrate

#332 Refactor `mdplain` package to use `yuin/goldmark` library for markdown processing
  go.mod
  go.sum
  internal/mdplain/mdplain.go
  internal/mdplain/mdplain_test.go
  internal/mdplain/renderer.go
  internal/mdplain/testdata/markdown.md
  internal/mdplain/testdata/mdplain.txt
Labels: dependencies, command/generate
