Repository hashicorp/terraform-plugin-docs, pull requests merged in 2024-04, with the labels that each got.

#358 Add `plainmarkdown` breaking change entry to `v0.19.0` changelog
  .changes/0.19.0.md
  CHANGELOG.md
Labels: documentation, command/generate

#357 Render attribute names for nested objected attributes correctly
  .changes/unreleased/BUG FIXES-20240417-171709.yaml
  cmd/tfplugindocs/testdata/scripts/schema-json/generate/framework_provider_success_all_framework_types.txtar
  cmd/tfplugindocs/testdata/scripts/schema-json/generate/framework_provider_success_nested_blocks.txtar
  internal/schemamd/render.go
  internal/schemamd/render_test.go
  internal/schemamd/testdata/framework_types.md
  internal/schemamd/testdata/framework_types.schema.json
Labels: bug, command/generate

#364 migrate: Ensure idempotency when ran multiple times
  .changes/unreleased/BUG FIXES-20240426-095042.yaml
  cmd/tfplugindocs/testdata/scripts/schema-json/migrate/time_provider_idempotency.txtar
  internal/provider/migrate.go
Labels: bug

#365 generate: Prevent automatic id attribute behaviors under blocks
  .changes/unreleased/BUG FIXES-20240426-111333.yaml
  cmd/tfplugindocs/testdata/scripts/schema-json/generate/nested_id_attribute.txtar
  internal/schemamd/render.go
Labels: bug
